### ISSUE TITLE
Optional dependence unit tests

### ISSUE THREAD

**Issue by aburrell** [aburrell/ocbpy#56]
The unit tests that require on pysat and DMSP SSJ modules aren't running on the CI platforms.

**Comment by aburrell** [comment]
pysat is still failing, likely due to pysatCDF installation issues.

**Comment by jklenzing** [comment]
Looking through the logs, I see this error popping up in the pysat-related tests:
```
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
This is likely due to a mismatch between netcdf and cftime versions in the current linux wheels on pip.  Documented in pysat/pysat#401.

This is part of the reason we migrated to conda to manage the install environment over there.  An alternative is to place a cap on netcdf and cftime versions.

**Comment by jklenzing** [comment]
OK.  tracked this down in a better fashion.  The netCDF4 wheel was compiled with a  newer version of numpy, which is capped at 1.15.4 (see #50) here.  This is where the numpy.ufunc error above is coming from.  Looking into possible fixes in my fork.  

Using a later version of numpy fixes the ufunc problem, but opens up the other issue documented in #50.  Because python 2.7 and 3.5 do not support later versions of numpy, this does not fix them.  I would lean toward dropping support for the older versions as it will be more difficult to maintain these in the future.  3.5 has reached the end of its lifecycle (final release November 1, 2019), and matplotlib and numpy have both dropped support for this.

**Comment by jklenzing** [comment]
Adding the pysat test instruments to the main package so that pysat 2.2 will have a pip-installable form for the unit tests here.   pysat/pysat#435

**Comment by aburrell** [comment]
@jklenzing so we need pysat>=2.2.0 for this, correct?

**Comment by jklenzing** [comment]
Yes.  You can install from the develop branch for now, but I think we've closed all the milestones but one.

**Comment by aburrell** [comment]
I will wait for the moment, I have one more issue I can work on here in the meantime.
